name: Build Packages

on: push

permissions:
  contents: write  # required by `action-gh-release`

env:
  python-version: "3.12"

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-12, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # required by `git describe`
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}
    - name: Install APT dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run build.py
      run: python build.py
    - name: Upload artifact  # upload to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: package-${{ matrix.os }}
        path: dist/*.*
        retention-days: 7
        compression-level: 0
        if-no-files-found: error
    - name: Upload release  # upload to GitHub Releases when a tag is pushed
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.*
        fail_on_unmatched_files: true
